name : Build and Release

on:
  push:
    # branches:
    #   - master #发版分支
    tags:
      - 'v*' #tag 发版
     
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 检查master分支
        uses : actions/checkout@master

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'

      - name: 安装依赖
        run: npm install

      - name: build打包
        run: npm run build
    
      # - name: 读取当前版本号
      #   id: version
      #   uses: ashley-taylor/read-json-property-action@v1.0
      #   with:
      #       path: ./package.json
      #       property: version
      
      # - name: 创建gitHub Release
      #   id: create_release
      #   uses: actions/create-release@latest
      #   env:
      #     GITHUB_TOKEN: ${{secrets.TOKEN}}
      #   with: 
      #      tag_name: v${{steps.version.outputs.value}}
      #      release_name: v${{steps.version.outputs.value}}
      #      draft: false
      #      prerelease: false
      
      # 发布到github提供的服务中去
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist